config/routes.rb
Rails.application.routes.draw do
  root 'payments#index'
  resources :members, except: :show
  resources :payments, only: [:index, :new, :create, :show] do
    member do
      patch :confirm
      get :print
    end
  end
  resources :plots, except: :show
  resources :dues, except: :show
  resource :setting, only: [:edit, :update]
  resources :transactions, except: :show do
    get :today_csv, on: :collection
  end
  resource :db, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/due.rb
# == Schema Information
#
# Table name: dues
#
#  id         :integer          not null, primary key
#  kind       :integer          not null
#  purpose    :string           not null
#  unit       :integer          not null
#  price      :decimal(, )      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Due < ApplicationRecord
  enum kind: [:entrance, :membership, :target, :custom]
  enum unit: [:per_square_meter, :per_plot, :per_member]

  has_many :transactions, inverse_of: :payable, as: :payable do
    def by_member(member)
      joins(:payment).where(payments: {member: member})
    end
  end
  has_and_belongs_to_many :members
  attr_accessor :select_all_members

  validates :kind, :purpose, :unit, :price, presence: true

  before_destroy do
    throw :abort unless can_be_destroyed?
  end

  # Returns a custom due which collects all non-standard transactions
  def self.custom
    find_by(id: Setting.config[:custom_due_id]) || create_custom_due!
  end

  def custom?
    id == Setting.config[:custom_due_id]
  end

  def self.create_custom_due!
    create!(
      kind: :custom,
      purpose: I18n.t('dues.custom.purpose'),
      unit: :per_member,
      price: 0
    ).tap do |due|
      Setting.set!(:custom_due_id, due.id)
    end
  end

  def altogether_for(member)
    return 0 unless member.dues.include?(self)
    send "calc_altogether_#{unit}", member
  end
  def calc_altogether_per_square_meter(member)
    price * member.space
  end
  def calc_altogether_per_plot(member)
    price * member.plots.count
  end
  def calc_altogether_per_member(member)
    price
  end

  def paid_so_far_by(member)
    transactions.by_member(member).pluck(:total).sum
  end

  def left_to_pay_by(member)
    altogether_for(member) - paid_so_far_by(member)
  end

  def can_be_destroyed?
    transactions.empty?
  end
end

app/controllers/dues_controller.rb
class DuesController < ApplicationController
  def index
    self.page_title = t 'dues.index.title'
    @entrance_dues = Due.entrance
    @target_dues = Due.target
    @membership_dues = Due.membership
  end

  def new
    self.page_title = t 'dues.new.title'
    @due = Due.new(kind: params[:kind], member_ids: Member.active.ids)
  end

  def create
    self.page_title = t 'dues.new.title'
    @due = Due.create(due_params)
    respond_with @due
  end

  def edit
    self.page_title = t 'dues.edit.title'
    @due = Due.find(params[:id])
  end

  def update
    self.page_title = t 'dues.edit.title'
    @due = Due.find(params[:id])
    @due.update(due_params)
    respond_with @due
  end

  def destroy
    @due = Due.find(params[:id])
    @due.destroy
    respond_with @due
  end

  def due_params
    params.require(:due).permit(:kind, :purpose, :unit, :price, member_ids: [])
  end
end

app/views/dues/_due.html.slim
tr
  td= link_to due.purpose, [:edit, due]
  td= Due.human_attribute_name "unit.#{due.unit}"
  td= number_to_currency due.price
  td
    - if due.can_be_destroyed?
      = link_to '&times;'.html_safe, due,
        method: :delete,
        data: {confirm: t('helpers.confirm_delete')},
        class: "btn btn-default"

app/views/dues/_form.html.slim
= simple_form_for @due do |f|
  = f.input :kind, collection: options_for_enum(Due, :kind)
  = f.input :purpose
  = f.input :unit, collection: options_for_enum(Due, :unit)
  = f.input :price
  - unless @due.entrance?
    = f.input :select_all_members, as: :boolean, include_hidden: false
    = f.association :members, as: :check_boxes, collection: Member.active.decorate, label: false
  = f.submit class: "btn btn-primary"

app/views/dues/_list.html.slim
h2= t "dues.index.#{kind}_dues"

table.table
  thead
    th= t 'activerecord.attributes.due.purpose'
    th= t 'activerecord.attributes.due.unit'
    th= t 'activerecord.attributes.due.price'
    th
  = render dues

app/views/dues/edit.html.slim
= render 'form'

app/views/dues/index.html.slim
p= link_to t('shared.form.add'), new_due_path

= render 'list', dues: @entrance_dues, kind: :entrance
= render 'list', dues: @target_dues, kind: :target
= render 'list', dues: @membership_dues, kind: :membership

app/views/dues/new.html.slim
= render 'form'