config/routes.rb
Rails.application.routes.draw do
  root 'payments#index'
  resources :members, except: :show
  resources :payments, only: [:index, :new, :create, :show] do
    member do
      patch :confirm
      get :print
    end
  end
  resources :plots, except: :show
  resources :dues, except: :show
  resource :setting, only: [:edit, :update]
  resources :transactions, except: :show do
    get :today_csv, on: :collection
  end
  resource :db, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :integer          not null, primary key
#  member_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_payments_on_member_id  (member_id)
#

class Payment < ApplicationRecord
  belongs_to :member
  has_many :transactions, inverse_of: :payment
  accepts_nested_attributes_for :transactions, reject_if: ->(hash) do
    hash[:total].blank?
  end
  default_scope { includes(:transactions) }

  def total
    transactions.map(&:total).sum
  end

  def next_transaction_number
    @next_transaction_number = if @next_transaction_number.nil?
       Transaction.next_number
    else
      @next_transaction_number + 1
    end
  end

  # Builds an array of new transactions,
  # one for each register or due of the payer
  # and merges in corresponding attributes
  # Usage:
  #   @transactions = @payment
  #     .new_transactions(payment_params[:transactions_attributes])
  def new_transactions(attributes={}, &block)
    hash = attributes.to_h.values.reduce({}) { |res, v|
      type = v["payable_type"].constantize
      id = v["payable_id"].to_i
      res[type] ||= {}
      res[type][id] = v
      res
    }

    (member.registers + member.dues).map { |payable|
      Transaction.new(
        (hash[payable.class][payable.id] || {} rescue {}).merge(
          payment: self,
          payable: payable,
        )
      )
    }.reject { |transaction|
      transaction.due? && transaction.fully_paid?
    }.reduce({}) { |res, t|
      res.tap do |r|
        r[t.payable.kind.to_sym] ||= []
        r[t.payable.kind.to_sym].push t
      end
    }
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  class PlotNotValidError < RuntimeError; end

  rescue_from PlotNotValidError do |e|
    redirect_back fallback_location: :payments, danger: e.message
  end

  before_action :load_payment, only: [:show, :confirm, :print]

  def index
    self.page_title = t('payments.title')
  end

  def new
    self.page_title = t('payments.new.title')
    @payment = Payment.new(member: member)
    @transactions = @payment.new_transactions
    @member = member.decorate
  end

  def create
    self.page_title = t('payments.new.title')
    @payment = Payment.create(payment_params)
    @transactions = @payment.new_transactions(transactions_params)
    @member = member.decorate
    respond_with @payment, location: -> { @payment }
  end

  def show
    self.page_title = t('payments.show.title')
  end

  def print
    @transactions = @payment.transactions
    if params[:transaction_id]
      @transactions = @transactions.where(transactions: {id: params[:transaction_id]})
    end
    @transactions = @transactions.decorate

    respond_to do |format|
      format.html do
        render layout: 'pdf'
      end
      format.pdf do
        render pdf: 'print',
          orientation: 'Landscape',
          page_size: 'A5',
          layout: 'pdf'
      end
    end
  end

  def confirm
    @payment.touch
    respond_with @payment, notice: t('.notice')
  end

  def load_payment
    @payment = Payment.find(params[:id])
  end

  def member
    @_member_cache ||= if params[:payment]
        Member.find(params[:payment][:member_id])
      else
        plot = Plot.find_by(number: params[:plot_number].upcase) or
          raise PlotNotValidError.new t('payments.no_such_plot')
        plot.member or
          raise PlotNotValidError.new t('payments.no_member')
      end
  end

  def payment_params
    params
      .require(:payment)
      .permit(
        :member_id,
        transactions_attributes: [
          :kind, :payable_id, :payable_type, :total, :start_display, :end_display, :difference]
      )
  end

  def transactions_params
    payment_params[:transactions_attributes]
  end
end

app/views/payments/_due_transactions.html.slim
- form
- transactions

- if transactions.present?
  h2= t "dues.index.#{transactions.first.due.kind}_dues"
  table.table
    thead
      th
      th= t 'payments.new.altogether'
      th= t 'payments.new.paid_so_far'
      th= t 'payments.new.left_to_pay'
      th= t 'payments.new.paying_now'
    tbody
      - transactions.each do |transaction|
        = form.fields_for :transactions, transaction do |ff|
          = ff.hidden_field :kind
          = ff.hidden_field :payable_id
          = ff.hidden_field :payable_type
          tr
            td
              p= transaction.due.purpose
              p
                => number_to_currency transaction.due.price
                = Due.human_attribute_name "unit.#{transaction.due.unit}"
            td= number_to_currency transaction.altogether
            td= number_to_currency transaction.paid_so_far
            td= number_to_currency transaction.left_to_pay
            td= ff.input :total, label: false

app/views/payments/_history.html.slim
- payments

h2= t 'payments.history.title'

- payments.each do |p|
  .row
    h3
      => l(p.created_at, format: :long) + " - "
      => number_to_currency p.total
    table.table
      thead
        tr
          th= Transaction.human_attribute_name(:number)
          th= Transaction.human_attribute_name(:kind)
          th= Transaction.human_attribute_name(:total)
          th
      - p.transactions.each do |t|
        tr
          td= t.number
          td= t.payable.class.human_attribute_name("kind.#{t.payable.kind}")
          td= number_to_currency t.total
          td= link_to t('.print'),
            [:print, t.payment, transaction_id: t.id, format: :pdf],
            class: "btn btn-link"

app/views/payments/_utility_transactions.html.slim
- form

table.table
  thead
    th= t 'payments.new.register'
    th= t 'payments.new.previous_display'
    th= t 'payments.new.current_display'
    th= t 'payments.new.difference'
    th= t 'payments.new.price_per_unit'
    th= t 'payments.new.total'
  tbody
    - [:electricity, :electricity_day, :electricity_night, :water].each do |kind|
      - (@transactions[kind] || []).each do |transaction|
        = form.fields_for :transactions, transaction do |ff|
          = ff.hidden_field :kind
          = ff.hidden_field :payable_id
          = ff.hidden_field :payable_type
          tr
            td= transaction.register.human_name
            td= ff.input :start_display, disabled: !transaction.start_display_edit_allowed?,
              label: false
            td= ff.input :end_display, label: false, disabled: !transaction.register.active
            td= ff.input :difference, label: false, disabled: !transaction.register.active
            td= number_to_currency Setting.config["price_#{transaction.register.kind}"]
            td= ff.input :total, label: false, disabled: !transaction.register.active

app/views/payments/index.html.slim
- unless Transaction.number_in_series?
  .alert.alert-warning= t 'errors.messages.transaction_id_not_in_series',
    missing: Transaction.missing_numbers.first(3).join(", ")
form action=new_payment_path
  .input-group
    input.form-control[type="text" id="plot_number" name="plot_number" autofocus="true"
      placeholder=t('payments.plot_number')]
    .input-group-btn
      button.btn.btn-default type="submit"
        i.glyphicon.glyphicon-search

app/views/payments/new.html.slim
.row
  .col-lg-12
    p #{t 'payments.new.plots'}: #{@member.plot_list}
    p #{t 'payments.new.space'}: #{@member.space}

.row
  .col-lg-6
    p #{link_to @member.fio, edit_member_path(@member)}<br>
      #{@member.address}<br>
      #{@member.phone}<br>
      #{@member.email}<br>
  .col-lg-6
    p #{t 'payments.new.dues_debt'}: #{number_to_currency @member.dues_debt}

- if @member.notes.present?
  pre.alert.alert-info
    = @member.notes
    = button_to t('payments.new.clear_notes'),
      [@member, member: {notes: nil}, back: request.original_url],
      method: :patch, class: 'pull-right'

- if @payment.errors.present?
  - @payment.errors.full_messages.each do |msg|
    .alert.alert-danger= msg

= simple_form_for @payment do |f|
  = f.hidden_field :member_id
  = render 'utility_transactions', form: f

  - Due.kinds.keys.map(&:to_sym).each do |kind|
    = render 'due_transactions', form: f, transactions: @transactions[kind]

  p= f.submit class: "btn btn-primary"
  p= link_to t('payments.new.create_custom_transaction'),
    [:new, :transaction, member_id: @payment.member_id]

app/views/payments/print.html.slim
= render partial: 'transactions/kpo', collection: @payment.transactions.decorate

app/views/payments/print.slim
= render partial: 'transactions/pko', collection: @transactions

app/views/payments/show.html.slim
.jumbotron.text-center
  h2= t 'payments.show.total'
  p: strong= number_to_currency @payment.total
  p
    = form_tag [:confirm, @payment], method: :patch
      button.btn.btn-primary.btn-lg autofocus=true type='submit' = t('payments.show.confirm')
  p= link_to t('.print'), print_payment_path(@payment, format: :pdf),
    target: "_blank", id: "print_payment_link"