config/routes.rb
Rails.application.routes.draw do
  root 'payments#index'
  resources :members, except: :show
  resources :payments, only: [:index, :new, :create, :show] do
    member do
      patch :confirm
      get :print
    end
  end
  resources :plots, except: :show
  resources :dues, except: :show
  resource :setting, only: [:edit, :update]
  resources :transactions, except: :show do
    get :today_csv, on: :collection
  end
  resource :db, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transactions/due_transaction.rb
module Transactions::DueTransaction
  extend ActiveSupport::Concern

  included do
    before_validation do
      if due?
        self.details = (self.details || {}).merge({
          due: due.attributes
        })
      end
    end

    validate do
      if due? && new_record? && !custom?
        if paid_so_far + total - altogether >= 0.01
          errors.add :total, "overpaying"
        end
      end
    end
  end

  def due
    payable
  end

  def altogether
    due.altogether_for(member)
  end

  def paid_so_far
    due.paid_so_far_by(member)
  end

  def left_to_pay
    due.left_to_pay_by(member)
  end

  def fully_paid?
    left_to_pay < 0.01
  end

  def custom?
    payable.custom?
  end
end

app/models/transactions/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id            :integer          not null, primary key
#  type          :string           not null
#  total         :decimal(, )      not null
#  price         :decimal(, )
#  start_display :integer
#  end_display   :integer
#  difference    :integer
#  details       :text             not null
#  payment_id    :integer
#  register_id   :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_transactions_on_payment_id   (payment_id)
#  index_transactions_on_register_id  (register_id)
#  index_transactions_on_type         (type)
#

class Transaction < ApplicationRecord
  belongs_to :payment

  validates :total, presence: true, numericality: {greater_than: 0}
  validates :details, presence: true

  serialize :details

  before_validation do
    self.details = (self.details || {}).merge({
      payer: payment.member.attributes.merge(
        plots: payment.member.plots.map(&:attributes)
      )
    })
  end

  def start_display_edit_allowed?
    register.start_display.nil?
  end
end

app/models/transactions/utility_transaction.rb
module Transactions::UtilityTransaction
  extend ActiveSupport::Concern

  included do
    before_validation do
      if utility?
        self.start_display ||= register.start_display || self.start_display || 0
        self.difference ||= self.start_display && self.end_display && (self.end_display - self.start_display)
        self.price = Setting.config["price_#{register.kind}"]
        self.details = (self.details || {}).merge({
          register: register.attributes.merge(
            plot: register.plot.attributes
          )
        })
      end
    end

    validate do
      if utility?
        if end_display && start_display and end_display - start_display != difference
          errors.add :difference, "invalid display"
        end
        if difference && total and difference * price != total
          errors.add :total, "mismatch"
        end
      end
    end
    validates :start_display, :end_display, :difference,
      presence: true, numericality: {only_integer: true, allow_nil: true}, if: -> { utility? }
    validates :price, presence:true, numericality: {greater_than: 0}, if: -> { utility? }
  end

  def register
    payable
  end
end

app/controllers/transactions_controller.rb
require 'csv'

class TransactionsController < ApplicationController
  def index
    self.page_title = t('transactions.index.title')
    @transactions = Transaction.order(number: :desc)
      .includes(:payable, payment: :member)
    @transactions = @transactions.this_year unless params[:all]
  end

  def today_csv
    csv_string = CSV.generate do |csv|
      Transaction.today.order(number: :desc).each do |t|
        csv << [t.number, t.member.fio, t.member.decorate.plot_list_text,
          t.decorate.ground, t.total]
      end
    end
    headers['Content-Disposition'] = 'attachment; filename="' + Time.zone.today.to_s + '.csv"'
    render text: csv_string, content_type: 'text/csv; charset=UTF-8'
  end

  def new
    self.page_title = t('transactions.new.title')
    @transaction = Transaction.new(
      number: Transaction.next_number,
      payable: Due.custom,
      payment: Payment.new(member_id: params[:member_id])
    )
  end

  def create
    self.page_title = t('transactions.new.title')
    @transaction = Transaction.create!(transaction_params.merge(
      payable: Due.custom
    ))
    respond_with @transaction
  end

  def edit
    self.page_title = t('transactions.edit.title')
    @transaction = Transaction.find(params[:id])
  end

  def update
    self.page_title = t('transactions.edit.title')
    @transaction = Transaction.find(params[:id])
    @transaction.update(transaction_params)
    respond_with @transaction
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    respond_with @transaction
  end

  def transaction_params
    params.require(:transaction).permit(
      :number,
      :start_display,
      :end_display,
      :difference,
      :price,
      :total,
      :purpose,
      :created_at,
      payment_attributes: [:member_id]
    )
  end
end

app/views/transactions/edit.html.slim
= simple_form_for @transaction do |f|
  = f.input :number
  = f.input :start_display
  = f.input :end_display
  = f.input :difference
  = f.input :price
  = f.input :total
  = f.input :created_at

  = f.submit class: "btn btn-primary"
  = link_to t('helpers.submit.delete'), @transaction, method: :delete,
    class: "btn btn-danger pull-right", data: {confirm: t('helpers.confirm_delete')}

app/views/transactions/index.html.slim
.row
  p.col-lg-6= link_to t('shared.form.add'), [:new, :transaction]
  p.col-lg-6
    => t 'transactions.index.paid_today', sum: number_to_currency(Transaction.paid_today)
    => link_to 'CSV', today_csv_transactions_path, target: '_blank'
    = link_to t('transactions.index.show_all'), '?all=true'

table.table
  thead
    tr
      th= Transaction.human_attribute_name(:number)
      th= Transaction.human_attribute_name(:member)
      th= Member.human_attribute_name(:plots)
      th= Transaction.human_attribute_name(:purpose)
      th= Transaction.human_attribute_name(:total)
      th= Transaction.human_attribute_name(:created_at)
      th
  - @transactions.each do |transaction|
    tbody
      tr
        td= link_to transaction.number, [:edit, transaction]
        td= link_to transaction.member.fio, [:edit, transaction.member]
        td= transaction.member.decorate.plot_list
        td= transaction.decorate.ground
        td= number_to_currency transaction.total
        td= l transaction.created_at, format: '%d.%m.%y'
        td= link_to t('.payment'), transaction.payment, class: "btn btn-link"

app/views/transactions/new.html.slim
= simple_form_for @transaction do |f|
  = f.input :number
  = f.fields_for :payment, @transaction.payment do |ff|
    = ff.association :member, collection: Member.active.decorate
  = f.input :total
  = f.input :purpose
  = f.input :created_at
  = f.submit class: "btn btn-primary"