config/routes.rb
Rails.application.routes.draw do
  root 'payments#index'
  resources :members, except: :show
  resources :payments, only: [:index, :new, :create, :show] do
    member do
      patch :confirm
      get :print
    end
  end
  resources :plots, except: :show
  resources :dues, except: :show
  resource :setting, only: [:edit, :update]
  resources :transactions, except: :show do
    get :today_csv, on: :collection
  end
  resource :db, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id         :integer          not null, primary key
#  fio        :string           not null
#  address    :string
#  phone      :string
#  email      :string
#  status     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  notes      :text             default(""), not null
#
# Indexes
#
#  index_members_on_status  (status)
#

class Member < ApplicationRecord
  enum status: [:active, :deleted]

  has_many :plots, -> { order :number }
  has_many :registers, through: :plots
  has_many :payments, -> { order created_at: :desc }
  has_and_belongs_to_many :dues
  attr_accessor :select_all_dues

  validates :fio, presence: true
  validates :status, presence: true

  default_scope { order(:fio).includes(:plots) }
  scope :active_plus_owner_of, ->(plot) {
    where("status = ? OR id = ?", statuses[:active], plot.member_id)
      .includes(:plots)
  }
  scope :didnt_pay_due, ->(due_id) {
    due = Due.find_by(id: due_id.to_i)
    if due.nil?
      all
    else
      members = Member.all.find_all { |m| due.left_to_pay_by(m) > 0 }
      where("id IN (?)", members.map(&:id))
    end
  }

  def self.owner_of(plot_number)
    Plot.find_by!(number: plot_number).member
  end

  def space
    plots.pluck(:space).sum
  end

  def dues_debt
    dues.map{|d| d.left_to_pay_by(self)}.sum
  end

  def destroy
    update(status: :deleted)
  end
  alias_method :destroy!, :destroy
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :load_resource

  def index
    self.page_title = t('members.index.title')
    @members = Member.active.includes(:plots)
      .didnt_pay_due(clean_params[:didnt_pay_due_id]).decorate
    @deleted_members = Member.deleted
      .didnt_pay_due(clean_params[:didnt_pay_due_id]).decorate
  end

  def new
    self.page_title = t('members.new.title')
    @member = Member.new(dues: Due.entrance)
  end

  def create
    self.page_title = t('members.new.title')
    @member = Member.create(member_params.merge(status: :active))
    respond_with @member
  end

  def edit
    self.page_title = t('members.edit.title', fio: @member.fio)
    self.page_title_link = [t('shared.to_payments'),
      [:new, :payment, plot_number: @member.plots.first.number]] unless
        @member.plots.empty?
  end

  def update
    self.page_title = t('members.edit.title', fio: @member.fio)
    @member.update(member_params)
    respond_with @member, location: -> { params[:back] }
  end

  def show
  end

  def destroy
    @member.destroy
    respond_with @member
  end

  def member_params
    params.require(:member).permit(:fio, :address, :phone, :email, :notes, due_ids: [])
  end

  def clean_params
    params.permit('didnt_pay_due_id')
  end
end

app/views/members/_form.html.slim
- if @member.deleted?
  .alert.alert-warning= t 'members.edit.warn_user_deleted'

= simple_form_for @member do |f|
  = hidden_field_tag :back, params[:back] || referer
  = f.input :fio
  = f.input :address
  = f.input :phone
  = f.input :email
  = f.input :notes
  = f.input :select_all_dues, as: :boolean
  = f.association :dues, as: :check_boxes, label: false,
    collection: Due.order(:kind, created_at: :desc),
    label_method: :purpose

  = f.submit class: "btn btn-primary"
  - if @member.persisted? && @member.active?
    = link_to t('helpers.submit.delete'), @member, method: :delete,
      class: "btn btn-danger pull-right", data: {confirm: t('helpers.confirm_delete')}

app/views/members/_list.html.slim
table.table.table-striped
  thead
    tr
      th= t('members.index.plots')
      th= t('members.index.fio')
      th= t('members.index.phone')
  - members.each do |member|
    tr
      td= member.plot_list
      td= link_to member.fio, [:edit, member]
      td= member.phone

app/views/members/edit.html.slim
= render 'form'
= render 'payments/history', payments: @member.payments

app/views/members/index.html.slim
p= link_to t('members.index.new'), new_member_path
p
  = form_for :debtors, method: :get do |f|
    = t('members.index.filter_by_due') + ": "
    = select_tag :didnt_pay_due_id, options_from_collection_for_select(Due.all, :id, :purpose, params[:didnt_pay_due_id]), include_blank: true
    = f.submit "OK"

= render 'list', members: @members

h2= t('members.index.inactive')
= render 'list', members: @deleted_members